In [1]:
import pandas as pd
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

#train_data_file = './train_data02.csv'
#train_data_file = './feature_importance/train_data_50.csv'
#train_data_file = './feature_importance/train_twoStep_50.csv'
train_data_file = './feature_importance/Final_train.csv'
test_data_file = './feature_importance/Final_val.csv'
train_data = pd.read_csv(train_data_file, encoding='utf-8')
test_data = pd.read_csv(test_data_file, encoding='utf-8')

In [2]:
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', 10)
print(train_data.shape)
print(test_data.shape)
#print(test_data.shape)
train_data.head()

(23432, 154)
(6675, 154)

,pax_fcny,pax_tax,tkt_3y_amt,dist_cnt_y1,dist_cnt_y3,avg_dist_cnt_y2,tkt_avg_amt_y3,dist_i_cnt_y3,avg_dist_cnt_y3,pref_city_y3_3,tkt_avg_amt_y2,tkt_i_amt_y3,pref_city_y3_2,dist_i_cnt_y2,seat_walkway_cnt_y3,dist_all_cnt_y2,pref_month_y3_1,pref_city_y2_2,pref_line_y3_3,pref_city_y2_3,tkt_all_amt_y3,avg_dist_cnt_y1,pref_month_y3_2,pref_line_y2_2,pref_line_y3_1,prebuy_i_cnt_y3_d99,pref_line_y3_4,pref_line_y3_2,seg_route_to,ffp_nbr,pref_orig_y3_3,flt_bag_cnt_y3,tkt_i_amt_y2,seat_middle_cnt_y3,pref_line_y2_1,seat_window_cnt_y3,pref_orig_city_y2,pref_month_y2_1,pref_line_y2_3,pref_line_y2_4,pref_month_y2_2,pref_month_y3_3,pref_orig_y3_2,tkt_all_amt_y2,age,flt_delay_time_m3,flt_delay_cnt_y3,pref_city_y1_2,pref_city_y3_4,prebuy_i_cnt_y2_d99,pit_avg_amt_y3,seat_walkway_cnt_y2,nation_name,pref_orig_y2_2,pref_month_y2_3,flt_bag_cnt_y2,pref_month_y3_4,pit_all_amt,pit_avg_amt_y2,pit_accu_air_amt,cabin_y_cnt_y3,cabin_hy_cnt_y3,pref_line_y1_2,pit_next_level_dist,flt_nature_cnt_y1,pref_city_y2_4,dist_all_cnt_y1,pref_orig_y2_3,dist_d_cnt_y3,pit_avg_accu_amt_y3,tkt_avg_amt_y1,flt_delay_time_y2,pit_avg_interval_y2,pref_city_y1_1,pref_line_y3_5,mdl_mcv,dist_i_cnt_y1,dist_all_cnt_y3,pit_accu_air_cnt,gender,tkt_book_cnt_y3,mdl_influence,flt_nature_cnt_y3,seat_middle_cnt_y2,select_seat_cnt_y2,flt_leg_i_cnt_y3,avg_dist_cnt_m6,tkt_d_amt_y3,pref_city_y1_3,pref_month_y3_5,cabin_y_cnt_y2,pref_orig_city_y3,pit_accu_amt_y3,prebuy_i_cnt_y3_d30,prebuy_i_cnt_y3_d3,flt_delay_time_m6,pref_month_y2_4,prebuy_d_cnt_y3_d99,pit_accu_amt_y2,pit_avg_interval_y3,seg_cabin,tkt_avg_interval_y3,flt_delay_time_y3,pref_month_y1_1,dist_i_cnt_m6,pref_line_y1_3,pit_add_air_amt_y3,pref_month_y2_5,flt_leg_cnt_y2,pit_accu_amt_y1,flt_delay_cnt_y2,pit_avg_accu_amt_y2,pref_city_y3_1,dist_all_cnt_m6,seat_window_cnt_y2,flt_cnt_y3,pref_line_y1_1,pref_orig_y3_1,flt_bag_cnt_y1,flt_leg_i_cnt_y2,prebuy_d_cnt_y2_d99,tkt_d_amt_y2,flt_delay_time_y1,tkt_avg_interval_y2,dist_d_cnt_y2,pref_orig_y1_1,cabin_hy_cnt_y2,pref_orig_city_y1,cabin_hf_cnt_m6,pref_orig_y3_4,pref_dest_city_y3,pit_accu_non_amt,tkt_book_cnt_y2,tkt_i_amt_y1,pref_city_y2_5,tkt_all_amt_y1,pref_city_y2_1,residence_country,pref_orig_y2_4,pit_add_air_amt_y2,prebuy_i_cnt_y3_d14,pref_orig_y1_2,tkt_return_cnt_y3,pit_avg_accu_amt_y1,pref_line_y2_5,pit_cons_amt_y3,prebuy_i_cnt_y2_d30,pref_orig_y3_5,pit_avg_amt_y1,pref_orig_city_m6,emd_lable2,emd_lable,pax_name,pax_passport
0,2497,5059,3,0,0,0,3,0,0,0,4,3,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,4,0,833,0,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,2,0,0,0,0,0,0,0,612,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,799,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,774,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9612c51f08718e48b1361e415ef55be9,93d0aceeaef3f85264e5c5b5b1148a90
1,1494,1544,3,0,0,835,5452,0,875,0,4599,4642,0,0,0,0,2,0,264,0,4722,1051,4,332,306,0,0,340,0,0,54,0,3772,0,305,2,0,2,238,0,4,0,52,3860,0,833,0,0,0,0,0,0,0,52,0,0,0,7,0,0,0,0,196,2,0,0,0,54,80,0,2094,612,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,1124,0,0,0,0,0,0,0,799,0,0,0,0,2,0,0,2,0,0,0,0,0,0,0,0,0,0,2,3,271,44,0,0,0,932,774,0,78,52,0,0,0,0,54,0,0,1524,0,1609,0,0,0,0,0,45,0,0,0,0,0,0,0,0,0,1,c7ca533cd9da4c4bf3d597248f90bc6e,6930f6fa59d86c11fa28c610ab6f56a5
2,214,2689,3,0,0,0,3,0,0,0,4,3,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,1,0,0,0,4,0,0,0,0,0,0,0,0,0,0,4,0,833,0,0,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,2,0,0,0,0,0,0,0,612,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,799,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,774,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,bd2cb6b0dd56fb3de6f7c018296a07e2,da73afa8f6ededd29d67a9331dccdbe9
3,1287,4452,3644,391,947,2925,5925,573,3380,0,4,4669,62,0,1,0,12,0,0,0,4594,0,1,0,99,2,0,244,1,0,0,2,4,0,0,1,0,0,0,0,0,0,62,4,0,833,0,0,0,0,0,0,0,0,0,0,0,7,0,0,2,0,0,2,1,0,0,0,0,0,0,612,0,0,0,5,0,947,0,0,0,0,2,0,0,2,0,0,0,0,0,50,0,0,0,799,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,46,0,0,2,0,44,0,0,0,1,774,0,0,0,0,0,0,0,43,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,65657872fe131ea7651565638dcb5683,dc31eead23771810dbb586ad236ade3b
4,645,2287,3682,0,1588,0,3,948,0,59,4,3,49,865,4,1533,0,49,0,57,3,0,0,0,0,4,0,0,0,11,0,4,4,0,0,0,79,0,0,0,0,0,0,4,0,833,0,0,0,4,0,4,0,0,0,4,0,7,0,0,0,0,0,2,0,0,0,0,0,0,0,612,0,0,0,0,0,1588,0,2,0,0,4,0,0,4,0,0,0,0,0,77,0,0,0,799,0,0,0,0,4,0,0,0,0,0,0,0,4,0,0,0,46,0,0,0,0,0,0,4,0,1,774,0,0,0,0,0,0,0,0,0,0,0,0,0,51,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,722261f7b860b183da9fe0b6630b6dbf,7689603247539830a08d945cb1a57823

In [3]:
strList = """pax_fcny	pax_tax	tkt_3y_amt	dist_cnt_y1	dist_cnt_y3	avg_dist_cnt_y2	tkt_avg_amt_y3	dist_i_cnt_y3	avg_dist_cnt_y3	tkt_avg_amt_y2	tkt_i_amt_y3	dist_i_cnt_y2	dist_all_cnt_y2	pref_city_y2_2	tkt_all_amt_y3	avg_dist_cnt_y1	pref_line_y2_2	pref_line_y3_1	pref_line_y3_4	pref_line_y3_2	tkt_i_amt_y2	pref_orig_city_y2	pref_line_y2_4	tkt_all_amt_y2	flt_delay_time_m3	pref_city_y3_4	pit_avg_amt_y3	nation_name	pit_all_amt	pit_avg_amt_y2	pit_accu_air_amt	pref_line_y1_2	pit_next_level_dist	dist_all_cnt_y1	dist_d_cnt_y3	pit_avg_accu_amt_y3	tkt_avg_amt_y1	pit_avg_interval_y2	pref_line_y3_5	dist_i_cnt_y1	dist_all_cnt_y3	mdl_influence	select_seat_cnt_y2	avg_dist_cnt_m6	tkt_d_amt_y3	pref_orig_city_y3	pit_accu_amt_y3	flt_delay_time_m6	pit_accu_amt_y2	pit_avg_interval_y3	tkt_avg_interval_y3	pref_line_y1_3	pit_add_air_amt_y3	pit_avg_accu_amt_y2	pref_city_y3_1	pref_line_y1_1	tkt_d_amt_y2	flt_delay_time_y1	tkt_avg_interval_y2	dist_d_cnt_y2	pref_orig_y3_4	pit_accu_non_amt	tkt_i_amt_y1	tkt_all_amt_y1	pref_city_y2_1	pref_orig_y2_4	pit_add_air_amt_y2	pref_line_y2_5	pit_cons_amt_y3	pit_avg_amt_y1"""
list1 = strList.split('\t')
print(len(list1))
#print(list)
test_data2 = test_data[list1]
print(test_data2.shape)
print(test_data.shape)

70
(6675, 70)
(6675, 154)

In [4]:
features_columns = [col for col in train_data.columns if col not in ['pax_name', 'pax_passport', 'emd_lable', 'emd_lable2']]
#features_columns = [col for col in train_data.columns if col not in ['pax_name', 'pax_passport', 'emd_lable2']]
#features_columns_test = [col for col in test_data.columns ]

train = train_data[features_columns].values
target =train_data['emd_lable2'].values

#test = test_data[features_columns].values
test = test_data2.values
print(test.shape)
#target =train_data['emd_lable'].values
target_test = test_data['emd_lable2'].values
print(target_test.shape)

(6675, 70)
(6675,)

In [5]:
from sklearn.feature_selection import SelectKBest
from array import array
from sklearn.feature_selection import chi2

train = SelectKBest(chi2, k=70).fit_transform(train, target)
print(train.shape)

train = pd.DataFrame(train)
train.head()

(23432, 70)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69
0,2497,5059,3,0,0,0,3,0,0,4,3,0,0,0,3,0,0,0,0,0,4,0,0,4,833,0,0,0,7,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,799,0,0,0,0,0,0,0,0,1,774,0,0,0,0,0,0,0,0,0,0,0,0
1,1494,1544,3,0,0,835,5452,0,875,4599,4642,0,0,0,4722,1051,332,306,0,340,3772,0,0,3860,833,0,0,0,7,0,0,196,2,0,80,0,2094,0,0,0,0,0,0,0,1124,0,0,799,0,0,0,0,0,0,0,271,932,774,0,78,0,0,1524,1609,0,0,0,0,0,0
2,214,2689,3,0,0,0,3,0,0,4,3,0,0,0,3,0,0,0,0,0,4,0,0,4,833,0,0,0,7,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,799,0,0,0,0,0,0,0,0,1,774,0,0,0,0,0,0,0,0,0,0,0,0
3,1287,4452,3644,391,947,2925,5925,573,3380,4,4669,0,0,0,4594,0,0,99,0,244,4,0,0,4,833,0,0,0,7,0,0,0,2,0,0,0,0,0,0,0,947,0,0,0,0,50,0,799,0,0,0,0,0,0,46,0,1,774,0,0,0,0,0,0,0,0,0,0,0,0
4,645,2287,3682,0,1588,0,3,948,0,4,3,865,1533,49,3,0,0,0,0,0,4,79,0,4,833,0,0,0,7,0,0,0,2,0,0,0,0,0,0,0,1588,0,0,0,0,77,0,799,0,0,0,0,0,0,46,0,1,774,0,0,0,0,0,0,51,0,0,0,0,0

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

clf = RandomForestClassifier(n_estimators=500, 
                             max_depth=71, 
                             random_state=0, 
                             n_jobs=-1)

X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.3, random_state=0)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
#print(test.shape, target_test.shape)

#验证集
clf = clf.fit(X_train, y_train)

print('=======')
y_true, y_pred = y_test, clf.predict(X_test)
#print(y_pred)
print(classification_report(y_true, y_pred))
print("RandomForest:", clf.score(X_test, y_test))
print('=======')

#print(clf.predict(X_test))

#设定阈值
threshold = 0.53
predicted_proba = clf.predict_proba(X_test)
print(predicted_proba.shape)
predicted = (predicted_proba [:,1] >= threshold).astype('int')#
accuracy = accuracy_score(y_test, predicted)
print(classification_report(y_test, predicted))
print("accuracy: ", accuracy)

pred_1d = predicted_proba[:,1].reshape(7030,)
y_test = y_test.reshape(7030,)
print(pred_1d.shape, y_test.shape)
print("AUC: ",roc_auc_score(y_true, pred_1d))


print(predicted.shape)
#predicted.reshape(9373,2)
data1 = predicted_proba.reshape(7030,2)

#print(train.shape, target.shape)
#print(test.shape, target_test.shape)

#测试集
print("test:")
clf.score(test, target_test)

print(clf.predict(test))
#data1 = clf.predict(test)
#print(clf.predict_proba(test))
data2 = clf.predict_proba(test)
data2.reshape(6675,2)

(16402, 70) (16402,)
(7030, 70) (7030,)
=======
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      6621
           1       0.65      0.27      0.38       409

    accuracy                           0.95      7030
   macro avg       0.80      0.63      0.68      7030
weighted avg       0.94      0.95      0.94      7030

RandomForest: 0.9489331436699858
=======
(7030, 2)
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      6621
           1       0.68      0.26      0.38       409

    accuracy                           0.95      7030
   macro avg       0.82      0.63      0.68      7030
weighted avg       0.94      0.95      0.94      7030

accuracy:  0.9499288762446657
(7030,) (7030,)
AUC:  0.7884873239883914
(7030,)
test:
[0 0 0 ... 0 0 0]

array([[0.786 , 0.214 ],
       [1.    , 0.    ],
       [0.982 , 0.018 ],
       ...,
       [0.9865, 0.0135],
       [0.72  , 0.28  ],
       [0.9   , 0.1   ]])

In [7]:
def find_repeat_data(name_list):
    """
    查找列表中重复的数据
    :param name_list: 
    :return: 一个重复数据的列表，列表中字典的key 是重复的数据，value 是重复的次数
    """
    repeat_list = []
    for i in set(name_list):
        ret=name_list.count(i) # 查找该数据在原列表中的个数
        if ret > 1:
            item=dict()
            item[i] = ret
            repeat_list.append(item)
    print(repeat_list)
    return repeat_list

find_repeat_data(list(y_test))
find_repeat_data(list(predicted))
#find_repeat_data(list())

[{0: 6621}, {1: 409}]
[{0: 6873}, {1: 157}]

[{0: 6873}, {1: 157}]

In [8]:
print(type(data1))
print(data1.shape)
print(pred_1d.shape)
#print(data2)
df = pd.DataFrame(data1)
df.insert(2, 'answer', list(pred_1d))  # 2表示插入列的位置（索引）， 'answer'是列标题
print(type(df))
print(df)
#df.to_csv('output_classifier.csv')

<class 'numpy.ndarray'>
(7030, 2)
(7030,)
<class 'pandas.core.frame.DataFrame'>
          0      1  answer
0     0.988  0.012   0.012
1     0.996  0.004   0.004
2     1.000  0.000   0.000
3     0.978  0.022   0.022
4     0.780  0.220   0.220
...     ...    ...     ...
7025  1.000  0.000   0.000
7026  0.936  0.064   0.064
7027  0.978  0.022   0.022
7028  0.988  0.012   0.012
7029  0.978  0.022   0.022

[7030 rows x 3 columns]

In [9]:
print(type(data2))
#print(data2)
df = pd.DataFrame(data2)
df.insert(2, 'answer', list(target_test))  # 2表示插入列的位置（索引）， 'answer'是列标题
print(type(df))
print(df)
#df.to_csv('output_classifier_test.csv')

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
             0         1  answer
0     0.786000  0.214000       0
1     1.000000  0.000000       0
2     0.982000  0.018000       0
3     0.960000  0.040000       0
4     0.999854  0.000146       0
...        ...       ...     ...
6670  1.000000  0.000000       0
6671  0.878000  0.122000       0
6672  0.986500  0.013500       0
6673  0.720000  0.280000       0
6674  0.900000  0.100000       0

[6675 rows x 3 columns]